// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package authndb

import (
	"context"
)

const listUserAuthn = `-- name: ListUserAuthn :many
SELECT id FROM authn
`

func (q *Queries) ListUserAuthn(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUserAuthn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
